### ISSUE TITLE
the slide windows

### ISSUE THREAD

**Issue by ghost** [imr-framework/mrf#3]
I noticed that you reconstruct the images by  using 48 or partial trajectory data,but the Nature paper "MRF" said the reconstruction only need a single trajectory data,so what's the reason of your solutions?

**Comment by qianenlin** [comment]
Thank you for posting the question! 

The MRF sequence designed in Sequence_Design part uses 48 shots of spirals. So by setting up the size of sliding window as 48, the selected trajectory will cover the full k-space, which will improve SNR and robustness of dictionary matching. 

A good reference will be [Cao et al., 2016](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.26521), please let me know if you have any questions!

**Comment by qianenlin** [comment]
@ouyangbinyu May I ask if I answered your question? If so, can I close the issue? Thank you!
